Text Classification: \
    1) ML approach\
    2) DL approach

Types of text classification:\
    1) binary (email spam)\
    2) multiclass\
    3) multilabel (eg: news, one value can come under multiple classes)

The pipeline:\

Data acquisition\
Text preprocessing (stemming, removing stopwords etc)\
Text vectorization (bag of words, tfidf, ngrams, word2vec etc)\
Modelling : ML(eg: Naive Bayes, random forest etc) or DL(RNN->LSTM, CNN, BERT)\
Evaluation (accuracy)\
Deploy


Approaches:\
    1)Heuristic approach (jugaad)\
    2)APIs\
    3)ML\
    4)DL (RNN: LSTM, CNN, pretrained models like BERT)\


### ML approach

In [3]:
import numpy as np
import pandas as pd

In [4]:
data=pd.read_csv('C:\\Users\\Vedashree\\Downloads\\IMDB_Dataset.csv')

In [6]:
temp_df=data.iloc[:10000]

In [7]:
temp_df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [8]:
temp_df['review'][2]

'I thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. The plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). While some may be disappointed when they realize this is not Match Point 2: Risk Addiction, I thought it was proof that Woody Allen is still fully in control of the style many of us have grown to love.<br /><br />This was the most I\'d laughed at one of Woody\'s comedies in years (dare I say a decade?). While I\'ve never been impressed with Scarlet Johanson, in this she managed to tone down her "sexy" image and jumped right into a average, but spirited young woman.<br /><br />This may not be the crown jewel of his career, but it was wittier than "Devil Wears Prada" and more interesting than "Superman" a great comedy to go see with friends.'

In [9]:
temp_df['sentiment'].value_counts()

positive    5028
negative    4972
Name: sentiment, dtype: int64

In [10]:
temp_df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [11]:
temp_df.duplicated().sum()

17

In [12]:
temp_df.drop_duplicates(inplace=True)

C:\Users\Vedashree\AppData\Local\Temp\ipykernel_18156\3757490955.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df.drop_duplicates(inplace=True)


In [13]:
temp_df.duplicated().sum()

0

In [16]:
# Basic preprocessing
# remove tags
# lowercase
# remove stopwords

In [17]:
import re
def remove_tags(raw_text):
    clean_text=re.sub(re.compile('<.*?>'),'',raw_text)
    return clean_text

In [18]:
temp_df['review']=temp_df['review'].apply(remove_tags)

C:\Users\Vedashree\AppData\Local\Temp\ipykernel_18156\1724238944.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df['review']=temp_df['review'].apply(remove_tags)


In [20]:
temp_df

review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. The filming tec...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
9995  Fun, entertaining movie about WWII German spy ...  positive
9996  Give me a break. How can anyone say that this ...  negative
9997  This movie is a bad movie. But after watching ...  negative
9998  This is a movie that was probably made to ente...  negative
9999  Smashing film about film-making. Shows the int...  positive

[9983 rows x 2 columns]

In [21]:
temp_df['review']=temp_df['review'].apply(lambda x:x.lower())

C:\Users\Vedashree\AppData\Local\Temp\ipykernel_18156\691844616.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df['review']=temp_df['review'].apply(lambda x:x.lower())


In [22]:
temp_df

review sentiment
0     one of the other reviewers has mentioned that ...  positive
1     a wonderful little production. the filming tec...  positive
2     i thought this was a wonderful way to spend ti...  positive
3     basically there's a family where a little boy ...  negative
4     petter mattei's "love in the time of money" is...  positive
...                                                 ...       ...
9995  fun, entertaining movie about wwii german spy ...  positive
9996  give me a break. how can anyone say that this ...  negative
9997  this movie is a bad movie. but after watching ...  negative
9998  this is a movie that was probably made to ente...  negative
9999  smashing film about film-making. shows the int...  positive

[9983 rows x 2 columns]

In [26]:
from nltk.corpus import stopwords

sw_list=stopwords.words('english')

temp_df['review']=temp_df['review'].apply(lambda x:[ item for item in x.split() if item not in sw_list])\
            .apply(lambda x:" ".join(x))

C:\Users\Vedashree\AppData\Local\Temp\ipykernel_18156\1134204924.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df['review']=temp_df['review'].apply(lambda x:[ item for item in x.split() if item not in sw_list])\


In [27]:
temp_df

review sentiment
0     one reviewers mentioned watching 1 oz episode ...  positive
1     wonderful little production. filming technique...  positive
2     thought wonderful way spend time hot summer we...  positive
3     basically there's family little boy (jake) thi...  negative
4     petter mattei's "love time money" visually stu...  positive
...                                                 ...       ...
9995  fun, entertaining movie wwii german spy (julie...  positive
9996  give break. anyone say "good hockey movie"? kn...  negative
9997  movie bad movie. watching endless series bad h...  negative
9998  movie probably made entertain middle school, e...  negative
9999  smashing film film-making. shows intense stran...  positive

[9983 rows x 2 columns]

In [28]:
X=temp_df.iloc[:,0:1]
Y=temp_df['sentiment']

In [30]:
X, Y #separated the columns

(                                                 review
 0     one reviewers mentioned watching 1 oz episode ...
 1     wonderful little production. filming technique...
 2     thought wonderful way spend time hot summer we...
 3     basically there's family little boy (jake) thi...
 4     petter mattei's "love time money" visually stu...
 ...                                                 ...
 9995  fun, entertaining movie wwii german spy (julie...
 9996  give break. anyone say "good hockey movie"? kn...
 9997  movie bad movie. watching endless series bad h...
 9998  movie probably made entertain middle school, e...
 9999  smashing film film-making. shows intense stran...
 
 [9983 rows x 1 columns],
 0       positive
 1       positive
 2       positive
 3       negative
 4       positive
           ...   
 9995    positive
 9996    negative
 9997    negative
 9998    negative
 9999    positive
 Name: sentiment, Length: 9983, dtype: object)

In [36]:
from sklearn.preprocessing import LabelEncoder

# converting positive, negative to 1,0
encoder=LabelEncoder()
y=encoder.fit_transform(Y)

In [34]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [35]:
from sklearn.model_selection import train_test_split

In [53]:
X_train,X_test, y_train, y_test=train_test_split(X,y,test_size=0.2,\
                                random_state=1)

In [54]:
X_train.shape

(7986, 1)

In [55]:
# Applying bag of words

from sklearn.feature_extraction.text import CountVectorizer

In [56]:
cv=CountVectorizer()

In [77]:
X_train_bow=cv.fit_transform(X_train['review']).toarray()
X_test_bow=cv.transform(X_test['review']).toarray()

In [78]:
X_train_bow.shape
# 48k features total

(7986, 48282)

In [71]:
from sklearn.naive_bayes import GaussianNB

gnb=GaussianNB()

gnb.fit(X_train_bow, y_train)

GaussianNB()

In [79]:
y_pred=gnb.predict(X_test_bow)



In [80]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(y_test, y_pred)

0.6324486730095142

In [81]:
confusion_matrix(y_test,y_pred)

array([[717, 235],
       [499, 546]], dtype=int64)

In [84]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(X_train_bow,y_train)
y_pred=rf.predict(X_test_bow)


In [85]:
accuracy_score(y_test,y_pred)

0.8452679018527791

In [87]:
cv2=CountVectorizer(max_features=5000) #5000 most frequent words

X_train_bow2=cv2.fit_transform(X_train['review']).toarray()
X_test_bow2=cv2.transform(X_test['review']).toarray()


In [88]:
rf=RandomForestClassifier()
rf.fit(X_train_bow2,y_train)
y_pred=rf.predict(X_test_bow2)


In [89]:
accuracy_score(y_test,y_pred)

0.8412618928392589

## TFIDF

In [90]:
from sklearn.feature_extraction.text import TfidfVectorizer


In [91]:
tfidf=TfidfVectorizer()

In [92]:
X_train_tfidf= tfidf.fit_transform(X_train['review']).toarray()
X_test_tfidf=tfidf.transform(X_test['review']).toarray()

In [93]:
rf=RandomForestClassifier()
rf.fit(X_train_tfidf,y_train)
y_pred=rf.predict(X_test_tfidf)
accuracy_score(y_test,y_pred)

0.8502754131196795

## using word2vec

In [94]:
import gensim
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [95]:
story=[]
for doc in temp_df['review']:
    raw_sent=sent_tokenize(doc)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [96]:
model=gensim.models.Word2Vec(window= 10, min_count=2)

In [97]:
model.build_vocab(story)

In [98]:
model.train(story,total_examples=model.corpus_count, epochs=model.epochs)

(5876319, 6212140)

In [99]:
len(model.wv.index_to_key)

31845

In [100]:
def document_vector(doc):
     # remove out of vocab words
    doc=[word for word in doc.split() if word in model.wv.index_to_key]
    return np.mean(model.wv[doc], axis=0)

In [101]:
document_vector(temp_df['review'].values[0])

array([-0.1790017 ,  0.48186967,  0.12880176,  0.23025894, -0.17798334,
       -0.6122521 ,  0.21627843,  0.9399599 , -0.3341686 , -0.2488956 ,
       -0.3030013 , -0.49260157,  0.14255913,  0.06952682,  0.1428597 ,
       -0.08186561,  0.00464929, -0.35076594, -0.07213341, -0.64421046,
        0.03244285,  0.22625941,  0.12710027, -0.275446  , -0.34339315,
       -0.00905702, -0.30558228, -0.01413643, -0.3491742 ,  0.01017526,
        0.36528295,  0.0351814 ,  0.21703725, -0.2796098 , -0.12195612,
        0.3747612 ,  0.12615322, -0.41189402, -0.26874635, -0.76801735,
        0.0923892 , -0.27335802,  0.09089863, -0.07777552,  0.4742127 ,
       -0.19340724, -0.27559987, -0.0229124 ,  0.10313671,  0.4039525 ,
        0.09636587, -0.35463214, -0.41339284, -0.08143559, -0.13813354,
        0.23408316,  0.25308293,  0.02091929, -0.30114615,  0.12288942,
        0.09604181,  0.11488391,  0.02694826, -0.09537393, -0.41284722,
        0.2482088 ,  0.05890553,  0.07785985, -0.31514773,  0.30

In [102]:
from tqdm import tqdm

In [103]:
Z=[]

for doc in tqdm(temp_df['review'].values):
    Z.append(document_vector(doc))

100%|██████████████████████████████████████████████████████████████████████████████| 9983/9983 [11:46<00:00, 14.14it/s]


In [110]:
Z=np.array(Z)

In [111]:
Z.shape

(9983, 100)

In [112]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

y2=encoder.fit_transform(temp_df['sentiment'])

In [113]:
X_train_w2v,X_test_w2v,y_train_w2v,y_test_w2v=train_test_split(
                                    Z,y2,test_size=0.2,random_state=1)

In [114]:
y2

array([1, 1, 1, ..., 0, 0, 1])

In [118]:
mnb=RandomForestClassifier()
mnb.fit(X_train_w2v,y_train_w2v)
y_pred_w2v= mnb.predict(X_test_w2v)

In [119]:
accuracy_score(y_test_w2v, y_pred_w2v)

0.771156735102654